#!/bin/sh
# Wrapper script for gprd CLI

# Set the PUBLIC_API environment variable
export PUBLIC_API="https://app.dev.guepard.run"

# Execute the actual application binary
# We will configure Cargo.toml to install the main binary to /usr/lib/guepard-cli/gprd
exec /usr/lib/guepard-cli/gprd "$@"