name: guepard
base: core22
version: '${VERSION}'
summary: Guepard CLI - Git-like filesystem for databases
description: |
  Guepard CLI provides a Git-like filesystem for databases, offering version control 
  and management capabilities for database schemas and data. It supports familiar 
  commands like init, commit, branch, checkout, and more.
  
  Features:
  - Git-like interface with familiar commands
  - Multi-platform support (Linux, macOS, Windows)
  - Database management and deployment
  - Cross-platform consistency

grade: stable
confinement: strict

parts:
  guepard:
    plugin: dump
    source: https://github.com/Guepard-Corp/guepard-cli/releases/download/${VERSION}/guepard-cli-${VERSION}-linux-amd64.tar.gz
    source-checksum: sha256/0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
    organize:
      guepard: bin/guepard

apps:
  guepard:
    command: bin/guepard
    plugs:
      - home
      - network
      - removable-media

slots:
  guepard:
    command: bin/guepard
    interface: content
    read:
      - $SNAP_USER_DATA
    write:
      - $SNAP_USER_DATA
