name: guepard
base: core22
version: '0.25.2'
summary: Guepard CLI - Git-like filesystem for databases
description: |
  Guepard CLI provides a Git-like filesystem for databases, offering version control 
  and management capabilities for database schemas and data. It supports familiar 
  commands like init, commit, branch, checkout, and more.
  
  Features:
  - Git-like interface with familiar commands
  - Multi-platform support (Linux, macOS, Windows)
  - Database management and deployment
  - Cross-platform consistency

grade: stable
confinement: strict

parts:
  guepard:
    plugin: dump
    source: https://github.com/Guepard-Corp/guepard-cli/releases/download/v0.25.2/guepard-cli-0.25.2-linux-amd64.tar.gz
    source-checksum: sha256/4815b4ab32ab9ed9824577446fd38ad2e0a6a170c672e46e2242c4ea564bf7aa
    organize:
      guepard: bin/guepard

apps:
  guepard:
    command: bin/guepard
    plugs:
      - home
      - network
      - removable-media

slots:
  guepard:
    command: bin/guepard
    interface: content
    read:
      - $SNAP_USER_DATA
    write:
      - $SNAP_USER_DATA
