name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cargo install --locked cargo-udeps

      - name: Check for unused dependencies
        run: cargo udeps

      - name: Run tests
        run: cargo test