name: Update macOS Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update packages for (e.g., 0.26.8)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew tap
        uses: actions/checkout@v4
        with:
          repository: Guepard-Corp/homebrew-guepard-cli
          token: ${{ secrets.GITHUB_TOKEN }}
          path: homebrew-tap

      - name: Download macOS releases
        run: |
          mkdir -p release-assets
          cd release-assets
          curl -L -o macos-arm64.tar.gz "https://github.com/Guepard-Corp/guepard-cli/releases/download/v${{ github.event.inputs.version }}-macos/guepard-cli-${{ github.event.inputs.version }}-macos-arm64.tar.gz"
          curl -L -o macos-amd64.tar.gz "https://github.com/Guepard-Corp/guepard-cli/releases/download/v${{ github.event.inputs.version }}-macos/guepard-cli-${{ github.event.inputs.version }}-macos-amd64.tar.gz"

      - name: Calculate SHA256 checksums
        run: |
          echo "MACOS_ARM64_SHA256=$(shasum -a 256 release-assets/macos-arm64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "MACOS_AMD64_SHA256=$(shasum -a 256 release-assets/macos-amd64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Update Homebrew formula
        run: |
          VERSION="${{ github.event.inputs.version }}"
          cat > homebrew-tap/Formula/guepard.rb << EOF
          class Guepard < Formula
            desc "Guepard CLI - Git-like filesystem for databases"
            homepage "https://www.guepard.run"
            url "https://github.com/Guepard-Corp/guepard-cli/releases/download/\${VERSION}/guepard-cli-\${VERSION}-macos-arm64.tar.gz"
            version "\${VERSION}"
            sha256 "${{ env.MACOS_ARM64_SHA256 }}"
            license "Guepard (c) 2025"

            on_macos do
              on_arm do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/\${VERSION}/guepard-cli-\${VERSION}-macos-arm64.tar.gz"
                sha256 "${{ env.MACOS_ARM64_SHA256 }}"
              end
              on_intel do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/\${VERSION}/guepard-cli-\${VERSION}-macos-amd64.tar.gz"
                sha256 "${{ env.MACOS_AMD64_SHA256 }}"
              end
            end

            def install
              bin.install "guepard"
            end

            test do
              system "#{bin}/guepard", "--version"
            end
          end
          EOF

      - name: Commit and push Homebrew formula
        run: |
          cd homebrew-tap
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/guepard.rb
          git commit -m "Update guepard to ${{ github.event.inputs.version }} (macOS)"
          git push
