name: Publish Homebrew

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.26.15)'
        required: true
        type: string

jobs:
  publish-homebrew:
    name: Generate Homebrew formula
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List available releases
        run: |
          echo "Available releases:"
          curl -s https://api.github.com/repos/Guepard-Corp/guepard-cli/releases | jq -r '.[].tag_name' | head -10

      - name: Set version
        id: ver
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Download all platform releases
        run: |
          mkdir -p release-assets
          cd release-assets
          curl -L -o macos-arm64.tar.gz "https://github.com/Guepard-Corp/guepard-cli/releases/download/v${{ steps.ver.outputs.version }}/guepard-cli-v${{ steps.ver.outputs.version }}-macos-arm64.tar.gz"
          curl -L -o macos-amd64.tar.gz "https://github.com/Guepard-Corp/guepard-cli/releases/download/v${{ steps.ver.outputs.version }}/guepard-cli-v${{ steps.ver.outputs.version }}-macos-amd64.tar.gz"
          curl -L -o linux-arm64.tar.gz "https://github.com/Guepard-Corp/guepard-cli/releases/download/v${{ steps.ver.outputs.version }}/guepard-cli-v${{ steps.ver.outputs.version }}-linux-arm64.tar.gz"
          curl -L -o linux-amd64.tar.gz "https://github.com/Guepard-Corp/guepard-cli/releases/download/v${{ steps.ver.outputs.version }}/guepard-cli-v${{ steps.ver.outputs.version }}-linux-amd64.tar.gz"

      - name: Calculate SHA256 checksums
        run: |
          echo "MACOS_ARM64_SHA256=$(shasum -a 256 release-assets/macos-arm64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "MACOS_AMD64_SHA256=$(shasum -a 256 release-assets/macos-amd64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "LINUX_ARM64_SHA256=$(shasum -a 256 release-assets/linux-arm64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "LINUX_AMD64_SHA256=$(shasum -a 256 release-assets/linux-amd64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Generate Homebrew formula
        run: |
          VERSION="${{ steps.ver.outputs.version }}"
          mkdir -p dist
          cat > dist/guepard.rb << EOF
          class Guepard < Formula
            desc "Guepard CLI (guepard) - Git, but for Data"
            homepage "https://www.guepard.run"
            url "https://github.com/Guepard-Corp/guepard-cli/releases/download/v\${VERSION}/guepard-cli-v\${VERSION}-macos-arm64.tar.gz"
            version "\${VERSION}"
            sha256 "${{ env.MACOS_ARM64_SHA256 }}"
            license "Guepard (c) 2025"

            on_macos do
              on_arm do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/v\${VERSION}/guepard-cli-v\${VERSION}-macos-arm64.tar.gz"
                sha256 "${{ env.MACOS_ARM64_SHA256 }}"
              end
              on_intel do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/v\${VERSION}/guepard-cli-v\${VERSION}-macos-amd64.tar.gz"
                sha256 "${{ env.MACOS_AMD64_SHA256 }}"
              end
            end

            on_linux do
              on_arm do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/v\${VERSION}/guepard-cli-v\${VERSION}-linux-arm64.tar.gz"
                sha256 "${{ env.LINUX_ARM64_SHA256 }}"
              end
              on_intel do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/v\${VERSION}/guepard-cli-v\${VERSION}-linux-amd64.tar.gz"
                sha256 "${{ env.LINUX_AMD64_SHA256 }}"
              end
            end

            def install
              bin.install "guepard"
            end

            test do
              system "#{bin}/guepard", "--version"
            end
          end
          EOF

      - name: Display generated formula
        run: |
          echo "Generated Homebrew formula for version ${{ steps.ver.outputs.version }}:"
          echo "=========================================="
          cat dist/guepard.rb
          echo "=========================================="
          echo ""
          echo "Copy the formula above and use it to update Homebrew Core manually."
