name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu,x86_64-apple-darwin,aarch64-apple-darwin,x86_64-pc-windows-msvc
          override: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libdbus-1-dev pkg-config

      - name: Build Linux AMD64
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          mkdir -p dist/linux-amd64
          cp target/x86_64-unknown-linux-gnu/release/guepard dist/linux-amd64/
          tar -czf dist/guepard-cli-${{ github.ref_name }}-linux-amd64.tar.gz -C dist linux-amd64/

      - name: Build Linux ARM64
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu
          mkdir -p dist/linux-arm64
          cp target/aarch64-unknown-linux-gnu/release/guepard dist/linux-arm64/
          tar -czf dist/guepard-cli-${{ github.ref_name }}-linux-arm64.tar.gz -C dist linux-arm64/

      - name: Build macOS AMD64
        run: |
          cargo build --release --target x86_64-apple-darwin
          mkdir -p dist/macos-amd64
          cp target/x86_64-apple-darwin/release/guepard dist/macos-amd64/
          tar -czf dist/guepard-cli-${{ github.ref_name }}-macos-amd64.tar.gz -C dist macos-amd64/

      - name: Build macOS ARM64
        run: |
          cargo build --release --target aarch64-apple-darwin
          mkdir -p dist/macos-arm64
          cp target/aarch64-apple-darwin/release/guepard dist/macos-arm64/
          tar -czf dist/guepard-cli-${{ github.ref_name }}-macos-arm64.tar.gz -C dist macos-arm64/

      - name: Build Windows AMD64
        run: |
          cargo build --release --target x86_64-pc-windows-msvc
          mkdir -p dist/windows-amd64
          cp target/x86_64-pc-windows-msvc/release/guepard.exe dist/windows-amd64/
          cd dist
          zip -r guepard-cli-${{ github.ref_name }}-windows-amd64.zip windows-amd64/

      - name: Calculate SHA256 checksums
        run: |
          cd dist
          echo "MACOS_ARM64_SHA256=$(shasum -a 256 guepard-cli-${{ github.ref_name }}-macos-arm64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "MACOS_AMD64_SHA256=$(shasum -a 256 guepard-cli-${{ github.ref_name }}-macos-amd64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "LINUX_ARM64_SHA256=$(shasum -a 256 guepard-cli-${{ github.ref_name }}-linux-arm64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "LINUX_AMD64_SHA256=$(shasum -a 256 guepard-cli-${{ github.ref_name }}-linux-amd64.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "WINDOWS_AMD64_SHA256=$(shasum -a 256 guepard-cli-${{ github.ref_name }}-windows-amd64.zip | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/guepard-cli-${{ github.ref_name }}-linux-amd64.tar.gz
            dist/guepard-cli-${{ github.ref_name }}-linux-arm64.tar.gz
            dist/guepard-cli-${{ github.ref_name }}-macos-amd64.tar.gz
            dist/guepard-cli-${{ github.ref_name }}-macos-arm64.tar.gz
            dist/guepard-cli-${{ github.ref_name }}-windows-amd64.zip
          tag_name: ${{ github.ref_name }}
          name: Guepard CLI ${{ github.ref_name }}
          body: |
            ## Guepard CLI ${{ github.ref_name }}

            ### Installation

            #### macOS (Homebrew)
            ```bash
            brew tap guepard-corp/guepard-cli
            brew install guepard
            ```

            #### Linux (Homebrew)
            ```bash
            brew tap guepard-corp/guepard-cli
            brew install guepard
            ```

            #### Windows (Chocolatey)
            ```powershell
            choco install guepard
            ```

            ### Supported Platforms
            - macOS (ARM64 + AMD64)
            - Linux (ARM64 + AMD64)
            - Windows (AMD64)

            ### SHA256 Checksums
            - macOS ARM64: `${{ env.MACOS_ARM64_SHA256 }}`
            - macOS AMD64: `${{ env.MACOS_AMD64_SHA256 }}`
            - Linux ARM64: `${{ env.LINUX_ARM64_SHA256 }}`
            - Linux AMD64: `${{ env.LINUX_AMD64_SHA256 }}`
            - Windows AMD64: `${{ env.WINDOWS_AMD64_SHA256 }}`

            ### What's New
            - Multi-platform support
            - Git-like filesystem for databases
            - Familiar command interface
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew tap
        uses: actions/checkout@v4
        with:
          repository: Guepard-Corp/homebrew-guepard-cli
          token: ${{ secrets.GITHUB_TOKEN }}
          path: homebrew-tap

      - name: Update Homebrew formula
        run: |
          VERSION="${{ github.ref_name }}"
          cat > homebrew-tap/Formula/guepard.rb << EOF
          class Guepard < Formula
            desc "Guepard CLI - Git-like filesystem for databases"
            homepage "https://www.guepard.run"
            url "https://github.com/Guepard-Corp/guepard-cli/releases/download/\${VERSION}/guepard-cli-\${VERSION}-macos-arm64.tar.gz"
            version "\${VERSION}"
            sha256 "${{ env.MACOS_ARM64_SHA256 }}"
            license "Guepard (c) 2025"

            on_macos do
              on_arm do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/\${VERSION}/guepard-cli-\${VERSION}-macos-arm64.tar.gz"
                sha256 "${{ env.MACOS_ARM64_SHA256 }}"
              end
              on_intel do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/\${VERSION}/guepard-cli-\${VERSION}-macos-amd64.tar.gz"
                sha256 "${{ env.MACOS_AMD64_SHA256 }}"
              end
            end

            on_linux do
              on_arm do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/\${VERSION}/guepard-cli-\${VERSION}-linux-arm64.tar.gz"
                sha256 "${{ env.LINUX_ARM64_SHA256 }}"
              end
              on_intel do
                url "https://github.com/Guepard-Corp/guepard-cli/releases/download/\${VERSION}/guepard-cli-\${VERSION}-linux-amd64.tar.gz"
                sha256 "${{ env.LINUX_AMD64_SHA256 }}"
              end
            end

            def install
              bin.install "guepard"
            end

            test do
              system "#{bin}/guepard", "--version"
            end
          end
          EOF

      - name: Commit and push Homebrew formula
        run: |
          cd homebrew-tap
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/guepard.rb
          git commit -m "Update guepard to ${{ github.ref_name }}"
          git push